name: Scala Steward
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v3
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.56.0
        with:
          repos-file: repos.md
          author-name: kchapl
          author-email: kchapl@users.noreply.github.com
          github-app-auth-only: true
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
